/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {
    // private static final String COMMA_DELIMITER = ",";



    public static void main(String[] args) {

        try {
            // List<List<String>> records = new ArrayList<>();
            // try (BufferedReader br = new BufferedReader(new FileReader("puzzle.csv"))) {
            //     String line;
            //     while ((line = br.readLine()) != null) {
            //         String[] values = line.split(COMMA_DELIMITER);
            //         records.add(Arrays.asList(values));
            //     }
            // }
            var p1="1..5.37..6.3..8.9......98...1.......8761..........6...........7.8.9.76.47...6.312";
            Puzzle.fromLine(p1);

            var c = new Puzzle.Cell();
            System.out.println(c);

            System.out.println(c);

        } catch (Exception e) {
            throw new RuntimeException(e);
        }

    }
}
